# Generated by Django 5.1.5 on 2026-04-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price_type',
            field=models.CharField(choices=[('day', 'Per Day'), ('month', 'Per Month')], default='month', max_length=10),
            preserve_default=False,
        ),
    ]
