# Generated by Django 5.1.5 on 2026-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_apartment_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='currency',
            field=models.CharField(choices=[('GMD', 'Dalasi'), ('USD', 'USD'), ('EUR', 'Euro')], default='GMD', max_length=5),
        ),
    ]
