# Generated by Django 5.1.5 on 2026-04-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_apartment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='phone',
            field=models.CharField(default='2200000000', max_length=20),
        ),
    ]
