# Generated by Django 5.1.5 on 2026-04-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_apartment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
