# Generated by Django 5.1.5 on 2026-04-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_apartment_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnishing',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished')], default='furnished', max_length=20),
        ),
        migrations.AddField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('apartment', 'Apartment'), ('house', 'House')], default='apartment', max_length=20),
        ),
    ]
