# Generated by Django 5.1.5 on 2026-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_apartment_bedrooms_apartment_furnishing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
