# Generated by Django 5.1.5 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
