# Generated by Django 5.1.5 on 2026-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
