# Generated by Django 5.1.5 on 2026-04-26 19:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_apartmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery_image'),
        ),
    ]
